# fly.toml app configuration file generated for classdore-scraper on 2025-10-15T23:46:02Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'classdore-scraper'
primary_region = 'iad'

[build]

[processes]
  scraper = "bash railway.sh"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
